# Manipulación de Datos en Python

## Lección 5: Funciones para conjuntar información en Pandas

### Concat y Append

In [27]:
import pandas as pd

df1 = pd.DataFrame({"A":["A0", "A1", "A2", "A3"],
                    "B":["B0","B1","B2","B3"],
                    "C":["C0","C1","C2","C3"],
                    "D":["D0","D1","D2","D3"]},
                   index=[0,1,2,3])

df4 = pd.DataFrame({"B":["B2","B3","B6","B7"],
                    "D":["D2","D3","D6","D7"],
                    "F":["F2","F3","F6","F7"]},
                   index=[2,3,6,7])

result = pd.concat([df1,df4], axis=1)
#result = result.set_axis(["A1","B1","C1","D1","B2","D2","F2"], axis = 1, copy=False)
print(result)

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [25]:
import pandas as pd

df1 = pd.DataFrame({"A":["A0", "A1", "A2", "A3"],
                    "B":["B0","B1","B2","B3"],
                    "C":["C0","C1","C2","C3"],
                    "D":["D0","D1","D2","D3"]},
                   index=[0,1,2,3])

df4 = pd.DataFrame({"B":["B2","B3","B6","B7"],
                    "D":["D2","D3","D6","D7"],
                    "F":["F2","F3","F6","F7"]},
                   index=[2,3,6,7])

result = pd.concat([df1,df4], axis=1, join="inner")
#result = result.set_axis(["A1","B1","C1","D1","B2","D2","F2"], axis = 1, copy=False)
print(result)#

   A1  B1  C1  D1  B2  D2  F2
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

Setting the index of columns

In [29]:
import pandas as pd

df1 = pd.DataFrame({"A":["A0", "A1", "A2", "A3"],
                    "B":["B0","B1","B2","B3"],
                    "C":["C0","C1","C2","C3"],
                    "D":["D0","D1","D2","D3"]},
                   index=[0,1,2,3])

df4 = pd.DataFrame({"B":["B2","B3","B6","B7"],
                    "D":["D2","D3","D6","D7"],
                    "F":["F2","F3","F6","F7"]},
                   index=[2,3,6,7])

result = pd.concat([df1,df4], axis=1)
result = result.set_axis(["A1","B1","C1","D1","B2","D2","F2"], axis = 1, copy=False)
print(result)

    A1   B1   C1   D1   B2   D2   F2
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

Right y Left join

In [31]:
import pandas as pd

df1 = pd.DataFrame({"A":["A0", "A1", "A2", "A3"],
                    "B":["B0","B1","B2","B3"],
                    "C":["C0","C1","C2","C3"],
                    "D":["D0","D1","D2","D3"]},
                   index=[0,1,2,3])

df4 = pd.DataFrame({"B":["B2","B3","B6","B7"],
                    "D":["D2","D3","D6","D7"],
                    "F":["F2","F3","F6","F7"]},
                   index=[2,3,6,7])

left_join = pd.concat([df1,df4], axis=1).reindex(df1.index)
right_join = pd.concat([df1,df4],axis=1).reindex(df4.index)
print(left_join, "\n\n", right_join)

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A3  B3  C3  D3   B3   D3   F3

      A    B    C    D   B   D   F
2   A2   B2   C2   D2  B2  D2  F2
3   A3   B3   C3   D3  B3  D3  F3
6  NaN  NaN  NaN  NaN  B6  D6  F6
7  NaN  NaN  NaN  NaN  B7  D7  F7

### Join y Merge